//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/InputAction/CircularMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CircularMovement : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CircularMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CircularMovement"",
    ""maps"": [
        {
            ""name"": ""Circle"",
            ""id"": ""41bcdfae-efaa-4de2-977b-0525346a846f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""364cbfdb-66ac-4c5a-88a9-8891eda4d4b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""bdc2f649-d3a5-4e1d-a974-98c61b7c7c35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch"",
                    ""type"": ""Button"",
                    ""id"": ""106136fa-715e-4a55-955c-3b0bfb2cb4c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""129bc871-ba4b-448c-a008-c8c7cdec2c5b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c056006a-5ecf-462a-8ab4-e5c6fb2b06a0"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4293335e-5460-4ff1-9421-bbdbd3042d1f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5cd4e0ae-6e2f-4c4a-a771-173523a42644"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4a88842a-67e0-479c-b61d-4ac941f28aa8"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Rotation_Circle"",
                    ""id"": ""a87e49d5-3bed-4a1b-98d3-55f3ec4db088"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""93126a66-65ea-42f8-a0e1-3fa890fc5dc8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""CircularScheme"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""f95dc086-00db-4012-947a-35139d4e6555"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""CircularScheme"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Switch_Circle"",
                    ""id"": ""862f8f8a-408f-414e-bf12-b29a9256d964"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7cd3f713-9d6d-4012-8e7e-bd2521ef9765"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""CircularScheme"",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""692b82e3-b5b8-40c7-bdb7-506ccc51a07c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""CircularScheme"",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""CircularScheme"",
            ""bindingGroup"": ""CircularScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Circle
        m_Circle = asset.FindActionMap("Circle", throwIfNotFound: true);
        m_Circle_Move = m_Circle.FindAction("Move", throwIfNotFound: true);
        m_Circle_Rotation = m_Circle.FindAction("Rotation", throwIfNotFound: true);
        m_Circle_Switch = m_Circle.FindAction("Switch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Circle
    private readonly InputActionMap m_Circle;
    private ICircleActions m_CircleActionsCallbackInterface;
    private readonly InputAction m_Circle_Move;
    private readonly InputAction m_Circle_Rotation;
    private readonly InputAction m_Circle_Switch;
    public struct CircleActions
    {
        private @CircularMovement m_Wrapper;
        public CircleActions(@CircularMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Circle_Move;
        public InputAction @Rotation => m_Wrapper.m_Circle_Rotation;
        public InputAction @Switch => m_Wrapper.m_Circle_Switch;
        public InputActionMap Get() { return m_Wrapper.m_Circle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CircleActions set) { return set.Get(); }
        public void SetCallbacks(ICircleActions instance)
        {
            if (m_Wrapper.m_CircleActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CircleActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CircleActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CircleActionsCallbackInterface.OnMove;
                @Rotation.started -= m_Wrapper.m_CircleActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_CircleActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_CircleActionsCallbackInterface.OnRotation;
                @Switch.started -= m_Wrapper.m_CircleActionsCallbackInterface.OnSwitch;
                @Switch.performed -= m_Wrapper.m_CircleActionsCallbackInterface.OnSwitch;
                @Switch.canceled -= m_Wrapper.m_CircleActionsCallbackInterface.OnSwitch;
            }
            m_Wrapper.m_CircleActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @Switch.started += instance.OnSwitch;
                @Switch.performed += instance.OnSwitch;
                @Switch.canceled += instance.OnSwitch;
            }
        }
    }
    public CircleActions @Circle => new CircleActions(this);
    private int m_CircularSchemeSchemeIndex = -1;
    public InputControlScheme CircularSchemeScheme
    {
        get
        {
            if (m_CircularSchemeSchemeIndex == -1) m_CircularSchemeSchemeIndex = asset.FindControlSchemeIndex("CircularScheme");
            return asset.controlSchemes[m_CircularSchemeSchemeIndex];
        }
    }
    public interface ICircleActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnSwitch(InputAction.CallbackContext context);
    }
}
